# Stubs for pkgutil

from types import ModuleType
from typing import Any, Callable, Generator, IO, Iterable, Iterator, Optional, Tuple, NamedTuple
import sys

if sys.version_info >= (3,):
    from importlib.abc import Loader
else:
    Loader = Any

if sys.version_info >= (3, 6):
    ModuleInfo = NamedTuple('ModuleInfo', [('module_finder', Any), ('name', str), ('ispkg', bool)])
    _YMFNI = Generator[ModuleInfo, None, None]
else:
    _YMFNI = Generator[Tuple[Any, str, bool], None, None]


def extend_path(path: Iterable[str], name: str) -> Iterable[str]: ...

class ImpImporter:
    def __init__(self, dirname: Optional[str] = ...) -> None: ...
    def find_module(self, fullname: str, path: str = ...) -> Optional[ImpLoader]: ...
    def iter_modules(self, prefix: str = ...) -> Iterator[Tuple[str, bool]]: ...

class ImpLoader:
    def __init__(self, fullname: str, file: IO[str], filename: str,
                 etc: Tuple[str, str, int]) -> None: ...
    def load_module(self, fullname: str) -> ModuleType: ...
    def get_data(self, pathname: str) -> bytes: ...
    def is_package(self, fullname: Optional[str] = ...) -> bool: ...
    def get_code(self, fullname: Optional[str] = ...) -> Any: ...
    def get_source(self, fullname: Optional[str] = ...) -> Any: ...
    def get_filename(self, fullname: Optional[str] = ...) -> Optional[str]: ...

def find_loader(fullname: str) -> Loader: ...
def get_importer(path_item: str) -> Any: ...  # TODO precise type
def get_loader(module_or_name: str) -> Loader: ...
def iter_importers(fullname: str = ...) -> Generator[Any, None, None]: ...  # TODO precise type
def iter_modules(path: Optional[Iterable[str]] = ...,
                 prefix: str = ...) -> _YMFNI: ...  # TODO precise type
def walk_packages(path: Optional[Iterable[str]] = ..., prefix: str = ...,
                  onerror: Optional[Callable[[str], None]] = ...) -> _YMFNI: ...
def get_data(package: str, resource: str) -> Optional[bytes]: ...
